version: 0.2

phases:
  install:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon EKS...
      - aws eks --region us-east-1 update-kubeconfig --name harbr-eks-demo-QPWM0dm9 
      # get commit hash
  build:
    commands:
      - echo Entered the build phase...
      - echo Change directory to secondary source
      # create namespace
      - kubectl create ns $EKS_NAMESPACE || true
      # set current namespace
      - kubectl config set-context $(kubectl config current-context) --namespace=$EKS_NAMESPACE 
      # apply kube specs
      - kubectl apply -f infra/k8s/